create table ctp_profile (
    id varchar(64) primary key,
    profile_code varchar(64) not null,
    username varchar(128) not null,
    display_name varchar(128) not null,
    avatar_url varchar(256),
    mock_customer_id varchar(64) not null,
    locale varchar(16) not null,
    supported_journey_types_json jsonb not null,
    status varchar(16) not null,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create unique index uk_ctp_profile_code on ctp_profile (profile_code);
create unique index uk_ctp_profile_username on ctp_profile (username);

create table ctp_chat_session (
    id varchar(26) primary key,
    profile_id varchar(64) not null references ctp_profile (id),
    title varchar(160) not null,
    status varchar(32) not null,
    workflow_state varchar(48) not null,
    journey_type varchar(48),
    message_count integer not null default 0,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create index idx_ctp_chat_session_profile_updated_at
    on ctp_chat_session (profile_id, updated_at desc);

create table ctp_chat_message (
    id varchar(26) primary key,
    session_id varchar(26) not null references ctp_chat_session (id) on delete cascade,
    sequence_no integer not null,
    role varchar(16) not null,
    message_type varchar(24) not null,
    content_text text,
    content_blocks_json jsonb,
    created_at timestamptz not null
);

create unique index uk_ctp_chat_message_session_sequence
    on ctp_chat_message (session_id, sequence_no);

create table ctp_payment_draft (
    id varchar(26) primary key,
    session_id varchar(26) not null unique references ctp_chat_session (id) on delete cascade,
    journey_type varchar(48) not null,
    status varchar(32) not null,
    workflow_state varchar(48) not null,
    source_account_id varchar(64) not null,
    source_account_display varchar(160) not null,
    payee_name_input varchar(160),
    payee_id_index varchar(128),
    payee_type varchar(32),
    payee_display varchar(160),
    amount numeric(18, 2),
    currency varchar(3),
    note varchar(280),
    review_summary_json jsonb,
    downstream_references_json jsonb,
    transfer_reference varchar(128),
    additional_context_json jsonb,
    candidate_payees_json jsonb,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table ctp_workflow_transition_log (
    id bigint generated by default as identity primary key,
    session_id varchar(26) not null references ctp_chat_session (id) on delete cascade,
    draft_id varchar(26) references ctp_payment_draft (id) on delete set null,
    from_state varchar(48),
    to_state varchar(48) not null,
    event_name varchar(48),
    action_name varchar(48),
    result_status varchar(24) not null,
    detail_json jsonb,
    created_at timestamptz not null
);

create index idx_ctp_workflow_transition_log_session_created_at
    on ctp_workflow_transition_log (session_id, created_at desc);
